name: Docs

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Docs Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: erlef/setup-beam@8251c48667b97e88a0a24ec512f5b72a039fcea7
        with:
          elixir-version: "1.16"
          otp-version: "27"
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-docs-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-docs-
      - run: mix deps.get
      - run: mix ci.docs
